### ISSUE TITLE
create docker image

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#6]
use offical nginx + official PHP docker images and cludge it together. It doesn't need to be nice, just work for development I guess... for nice we use the (production) deploy in the deployment repo.

**Comment by fkooman** [comment]
no longer relevant, this will be done by IndieHosters most likely, I have no real interest in this...

**Comment by pataquets** [comment]
@fkooman Any change on this? I'm about to try this software and I might need to hack/contrib/fix something and I'm into the Docker workflow (as I code in several languages and don't want to install devtools/toolchains locally), and I would like to know.
I'll be happy to contribute my Dockerfile & docs if I finally got into it. I've looked at the old Dockerfile, but I guess it'll be better to start over with some image more baked already, such as [composer](https://hub.docker.com/_/composer/).

**Comment by fkooman** [comment]
No change, I am still not interested in it, after 7 years Docker is still garbage. Although I must say that tooling like [podman](https://podman.io/) make it more interesting to look at containers.

Feel free to create and maintain your own `Dockerfile`.

**Comment by raucao** [comment]
@fkooman Thanks for offering your feedback. I can't say I disagree entirely. :)

@pataquets Since Docker is still wildly popular, and many people might want to deploy the software that way, please don't hesitate to share your Docker repo with other users. Maybe you could do a pull request for linking it in the README here, but you can also definitely add information to https://remotestorage.io/servers/ (which already links some Docker image actually, but no idea if that will be updated for the next release version).
